"""empty message

Revision ID: cbf7718fd897
Revises: ff494e9e7457
Create Date: 2016-12-21 06:35:02.283686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf7718fd897'
down_revision = 'ff494e9e7457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('disk', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'disk')
    # ### end Alembic commands ###
